- name: Playbook2
  hosts: dev
  remote_user: root
  tasks:
  - name: test de connexion
    ping:
  - name: creation d'un dossier
    file:
      path: /exo-ansible
      state: directory
      owner: root
      group: root
      mode: 0755
  - name: creation d'un fichier
    file:
      path: /exo-ansible/mmi22d06.txt
      state: touch
      mode: 0600